#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <pthread.h>
#include <math.h>
#include <limits.h>
#include <string.h>
#include <pthread.h>
#include <time.h>
#include <locale.h>
#include <time.h>
#include <unistd.h>
#include <windows.h>
#include <semaphore.h>